# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudiantes', '0002_auto_20171020_0425'),
        ('Instituciones', '0002_auto_20171019_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Latitud', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Longitud', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Admin', models.BooleanField(default=False)),
                ('SS_Admin', models.BooleanField(default=False)),
                ('Horas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('horario', models.CharField(max_length=100)),
                ('requisitos', models.CharField(max_length=500)),
                ('estudiantes', models.ManyToManyField(to='Estudiantes.Estudiantes')),
                ('institucion', models.ManyToManyField(to='Instituciones.Instituciones')),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clases.Clases'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.Estudiantes'),
        ),
    ]
