# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='Horas',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
