# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudiantes', '0002_auto_20171020_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSClases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('horario', models.CharField(max_length=100)),
                ('requisitos', models.CharField(max_length=500)),
                ('estudiantes', models.ManyToManyField(to='Estudiantes.Estudiantes')),
            ],
        ),
    ]
