# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='SSUsuarios',
        ),
    ]
